# Generated by Django 4.1.7 on 2023-10-20 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concert", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 20, 14, 54, 30, 837270)
            ),
        ),
    ]
