# Generated by Django 4.1.7 on 2023-10-21 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concert", "0003_alter_concert_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 21, 14, 19, 22, 160961)
            ),
        ),
    ]
